# <div align="center"> Statistical learning </div>
# <div align="center"> Machine Learning and Econometrics  </div>
## <div align="center"> ECO 4971/6971  </div>
#### <div align="center">Class 12 — Deep Learning</div>
<div align="center"> Jonathan Holmes (he/him)</div>

### TODAY: Introduction to Deep Learning

- **Hands-on in this deck:** *Hands on with a deep neural network* — a tiny network for a **scholarship** example (GPA and extracurriculars) **before** *What's deep in DL?*

### NEXT CLASS: Hands On with Tensor Flow

Tutorial: [TensorFlow — Regression](https://www.tensorflow.org/tutorials/keras/regression) (same notebook can run in **Google Colab** from the link, or locally).

- **Local install:** e.g. `conda install tensorflow` or `pip install tensorflow` (choose a build that matches your Python version and hardware).

# Deep Learning
- **Deep learning** (DL) powers many recent AI advances—e.g. perception systems, image and speech models, and generative tools (including “deepfakes,” both useful and problematic).

- In this class we treat **deep learning** and **artificial neural networks** (with more than one hidden layer, or a deep stack of computations) as essentially the same topic.

**Additional resources:**
- Goodfellow, Bengio & Courville, [_Deep Learning_](https://www.deeplearningbook.org/) (free online; mathematically dense).
- [Kaggle: Intro to Deep Learning](https://www.kaggle.com/learn/intro-to-deep-learning) (short, hands-on lessons).

## How does a human brain understand numbers? 

<div align="center"> <img src="https://www.dropbox.com/scl/fi/bonrk4qgh114q0h94iudq/numbers.png?rlkey=vd3gflun8a2hum66m0hy33yvw&dl=1" width=600 height=600 /> </div>





1. The eyes encode light, contrast, and color.
2. Early visual areas organize that input into edges and shapes.
3. Higher visual areas support recognition—including symbols such as digits (loosely analogous to “features” in a learned representation).

## From human brains to computers

Neural networks follow the same **hierarchical** idea:

1. Start from raw inputs.
2. Learn intermediate **representations** (sometimes called “features”).
3. Map those representations to an output (prediction, probability, class, etc.).

#### Notes
- The model learns its own internal representation; we do not hand-craft polynomial or interaction terms as in linear regression.
- **Interpretability** is limited: individual weights are often hard to map to a clean economic story—use simpler models when credible **causal** interpretation matters most.



## What's deep in DL?
$$y=f(X) + \varepsilon$$


- Deep learning includes multiple nested functions:
$$f^\ast(x)= f^{(3)}(f^{(2)}(f^{(1)}(x)))$$

- Such **chains** (compositions of functions) define a __feedforward neural network__. 
    - $f^{(1)}$ is the first __hidden layer__ (first transformation of the inputs).
    - $f^{(2)}$, $f^{(3)}$, … are deeper layers—each builds on the previous representation.
    
- You can think of deeper layers as **higher-level** abstractions built from simpler ones.

## A single layer neural network

<div align="center"> <img src="https://www.dropbox.com/scl/fi/6yb13tugjelne7dxjs33f/neural_network1.png?rlkey=f276sefexlunyuxasqwn14ebo&dl=1" width=500 height=500 /> </div>

1. Input layer is data
2. Hidden layer is functions of the data
3. Output layer is the prediction



# What's a neuron in a neural network?

<div align="center"> <img src="https://www.dropbox.com/scl/fi/9focpks0mj0wa1jm2thuq/fig1_unit.png?rlkey=pohn6vme7h52yc2sq6qca3bom&dl=1" width=500 height=500 /> </div>

- This is an artificial __neuron__
    - Synonyms: __node__, __unit__

- Neurons represent functions: 
    - Inputs X and a constant
    - Output Y




## Linear regression and the linear unit
- Simplest **neuron** (no nonlinearity): a linear unit—i.e. linear regression on one feature:
    -  $y = w x + b$ 
- This is the equation of a line:
     - w is a __weight__ (Econometrics: the slope $\beta$)
     - b is a __bias__ (Econometrics: the intercept $\alpha$)
- Too many definitions for __bias__!
    - Econometrics: When $E[\hat{\beta}] \neq \beta$ 
    - Statistical learning: When the model $\hat{f}(x)$ is not flexible enough to fit the real $f(x)$
    - Neural networks: Bias = Coefficient on constant term (Intercept)

## Multiple Inputs 

- You can simply add more input __connections__ to the neuron, one for each additional feature. 
  - $y = w_0 x_0 + w_1 x_1 + w_2 x_2 + b$
  
- In this display there are **three** input weights $(w_0,w_1,w_2)$ and **one** bias $b$ (some texts absorb $b$ into a constant input—notation varies).

## Other functions

Typically each neuron applies an **affine** map (weighted sum plus bias) and then a **nonlinear** activation $g$: 
$$ y = h(x) = g(w_0x_0 + w_1x_1 + \cdots + w_Nx_N + b). $$ 

Common choices for $g$: 
- **Sigmoid:** $g(z) = \dfrac{1}{1+e^{-z}} = \dfrac{e^z}{1+e^z}$ (squashes $z$ into $(0,1)$; historically popular; can saturate).
- **ReLU (rectified linear unit):** $g(z) = \max(0, z)$—simple, often works well in practice.
- Many others exist (tanh, GELU, etc.) depending on architecture and task.

## What's going on? 


<div align="center"> <img src="https://www.dropbox.com/scl/fi/6yb13tugjelne7dxjs33f/neural_network1.png?rlkey=f276sefexlunyuxasqwn14ebo&dl=1" width=600 height=600 /> </div>

- Each neuron in an intermediate layer is a function of the inputs.
- Example: $A_1 = h_1(X)$, …, $A_5 = h_5(X)$.
- Output $Y = f(A_1, A_2, \ldots, A_5)$.




## In-class exercise

**Q1.** In the schematic network above, how many **input features** $(X_1,\ldots,X_4)$ are there? How many **hidden units** $(A_1,\ldots,A_5)$?


**Q2.** Count **trainable parameters** (weights + biases):
- For **each** hidden neuron $h_k$: how many weights and how many biases?

- If the output is a **linear** function of $(A_1,\ldots,A_5)$, e.g.
$$f(X) = \beta_0 + \beta_1 A_1 + \cdots + \beta_5 A_5,$$
how many parameters in the output layer?

- **Total** parameters in this toy network?

**Q3.** Why stack **nonlinear** activations $g$ instead of leaving every unit purely linear?



## Neural networks and neuroscience (informal analogy)

People sometimes borrow **brain** language:
- After certain activations (e.g. sigmoid), a unit near 0 can be described as __“silent”__; a unit that is large or near 1 might be described as strongly __“on”__ or __firing__.

In practice for **modeling**:
- Activations in __hidden layers__ are **not** directly interpreted like regression coefficients.
- We mainly judge the fitted model on **predictive** performance (and proper validation)—keeping claims about **causal** channels disciplined, as elsewhere in the course.




## Hands on with a deep neural network

### The problem (illustration)

Suppose we want to model **whether a student receives a scholarship** using two inputs: **GPA** and a summary measure of **extracurricular involvement** (hours, leadership score, etc.—here we treat it as a single numeric index).

We suspect the mapping from $(\text{GPA}, \text{extracurriculars})$ to the chance of a scholarship is **nonlinear**—for example, very high achievement on **one** dimension might not compensate for a very weak showing on the other, or thresholds might matter. We **do not** specify a particular functional form (no pre-chosen polynomial or interaction formula); we only want a **flexible** mapping.

A **small feedforward network** can already produce a **nonlinear** surface over the two inputs, even with only **two hidden units**—as long as we include a **nonlinear activation** in the hidden layer.


### A tiny network: 2 inputs → 2 hidden units → 1 output

Let $x_1$ be GPA and $x_2$ the extracurricular index (you can imagine them **standardized** or on fixed scales). With weights $w^{(1)}_{ij}$, hidden biases $b^{(1)}_j$, output weights $v_j$, output bias $b^{(2)}$, and the **same** logistic **sigmoid** $\sigma$ at the hidden units and again at the output (one functional form, applied twice):

$$z^{(1)}_1 = w^{(1)}_{11} x_1 + w^{(1)}_{12} x_2 + b^{(1)}_1, \quad a^{(1)}_1 = \sigma(z^{(1)}_1)$$
$$z^{(1)}_2 = w^{(1)}_{21} x_1 + w^{(1)}_{22} x_2 + b^{(1)}_2, \quad a^{(1)}_2 = \sigma(z^{(1)}_2)$$
$$z^{(2)} = v_1 a^{(1)}_1 + v_2 a^{(1)}_2 + b^{(2)}, \quad \hat{y} = \sigma(z^{(2)})$$

Here $\hat{y}$ is a **predicted probability** (scholarship). **Without** $\sigma$ in the hidden layer (if hidden activations were the identity), the map from $(x_1,x_2)$ to $z^{(2)}$ would stay **affine**—a single linear decision in the inputs. **With** nonlinear $\sigma$ in the hidden layer, even **two** hidden units can **bend** the surface and approximate nontrivial shapes over the plane.

The next cell turns these symbols into code: edit the **arrays** for weights and biases, re-run, and inspect the **3D** surface of $\hat{y}$ over GPA and extracurriculars. Default coefficients are chosen so that **higher GPA** and **higher extracurricular involvement** both correspond to **higher** predicted probability of a scholarship (on the plotted grid). The figure is **interactive**: with **Plotly** (`pip install plotly` if needed), drag to **rotate** and scroll to **zoom**; if Plotly is missing, the cell falls back to a static Matplotlib surface and prints a short install hint.


In [ ]:
import numpy as np

# --- edit coefficients below. With all entries of W_h and w_out positive, increasing GPA
#     or extracurriculars pushes P(scholarship) up (monotone on this grid). ---
# Hidden: W_h[j,:] = weights for unit j on (GPA, extracurricular); b_h[j] = bias
W_h = np.array(
    [
        [0.90, 0.50],
        [0.70, 0.65],
    ]
)
b_h = np.array([-3.50, -4.00])

# Output: positive weights → higher hidden activations → higher logit before sigmoid
w_out = np.array([3.00, 3.00])
b_out = -2.00


def sigmoid(z):
    """Logistic; used at hidden units and at the output (same function throughout)."""
    return 1.0 / (1.0 + np.exp(-z))


def scholarship_prob(gpa, extracurricular):
    """Vectorized: gpa and extracurricular can be scalars or 2D grids (meshgrid)."""
    z1 = W_h[0, 0] * gpa + W_h[0, 1] * extracurricular + b_h[0]
    z2 = W_h[1, 0] * gpa + W_h[1, 1] * extracurricular + b_h[1]
    a1 = sigmoid(z1)
    a2 = sigmoid(z2)
    z_out = w_out[0] * a1 + w_out[1] * a2 + b_out
    return sigmoid(z_out)


# Grid (GPA in [2, 4], extracurricular index in [0, 10])
gpa_grid = np.linspace(2.0, 4.0, 60)
extra_grid = np.linspace(0.0, 10.0, 60)
GPA, EXTRA = np.meshgrid(gpa_grid, extra_grid)
Y_hat = scholarship_prob(GPA, EXTRA)

# Interactive 3D: drag to rotate / scroll to zoom (Plotly). Fallback: static Matplotlib.
try:
    import plotly.graph_objects as go

    fig = go.Figure(
        data=[
            go.Surface(
                x=gpa_grid,
                y=extra_grid,
                z=Y_hat,
                colorscale="Viridis",
                showscale=True,
                colorbar=dict(title="P(scholarship)"),
            )
        ]
    )
    fig.update_layout(
        title="P(scholarship) — drag to rotate, scroll to zoom",
        scene=dict(
            xaxis_title="GPA",
            yaxis_title="Extracurricular index",
            zaxis_title="P(scholarship)",
            aspectmode="manual",
            aspectratio=dict(x=1, y=1, z=0.55),
            camera=dict(eye=dict(x=1.35, y=-1.65, z=0.85)),
        ),
        height=560,
        margin=dict(l=0, r=0, t=50, b=0),
    )
    fig.show()
except ImportError:
    import matplotlib.pyplot as plt

    print(
        "Plotly not installed — showing a static Matplotlib surface.\n"
        "For an interactive (rotatable) plot: pip install plotly\n"
        "Or try: %matplotlib widget  (pip install ipympl) and use matplotlib in notebook mode."
    )
    fig = plt.figure(figsize=(9, 6))
    ax = fig.add_subplot(projection="3d")
    surf = ax.plot_surface(
        GPA,
        EXTRA,
        Y_hat,
        cmap="viridis",
        edgecolor="none",
        alpha=0.95,
    )
    ax.set_xlabel("GPA")
    ax.set_ylabel("Extracurricular index")
    ax.set_zlabel(r"$\hat{y}$ = P(scholarship)")
    fig.colorbar(surf, ax=ax, shrink=0.55, label=r"$\hat{y}$")
    plt.tight_layout()
    plt.show()


## Training a deep neural network (sketch)

You (or software defaults) choose **architecture**: 
- How many layers and neurons
- Which activation functions $g$
- A **loss** (e.g. MSE for regression, cross-entropy for classification) and an **optimizer**.

**Typical loop:** 
1. Initialize weights and biases (often at random, with careful scaling).
2. For many **epochs** / steps:
    - **Forward pass:** compute predictions and loss.
    - **Backward pass:** use the chain rule (**backpropagation**) to get **gradients** of the loss w.r.t. each parameter.
    - **Update:** move $w$, $b$ a small step opposite the gradient (**gradient descent** or variants such as **SGD**, Adam, …).



## Terminology

- **Backpropagation:** Efficient application of the chain rule to compute **gradients** of the loss with respect to all parameters.
- **Gradient descent (and variants):** Use those gradients to update parameters so the loss (usually) decreases step by step.
- **Epoch:** One full pass over the training data (definitions can vary slightly when using mini-batches; sometimes people say “step” for one update).



## Advantages of neural networks

In previous classes, we made linear models more flexible by adding: 
- Polynomial terms (e.g. $X_1^2$, $X_1^3$)
- Interaction terms (e.g. $X_1 X_2$, $X_1^2 X_2$)

Neural networks can be _far_ more flexible
- The algorithm decides how to combine/interact variables
- It's possible to have discontinuous, non-linear, interacting, complex relationships



## In-class exercise

**Q4.** You want good **out-of-sample** predictions and are choosing among OLS, Lasso, and a neural net. How do you decide?


**Q5.** Same task, but **100× more** training data. What changes?




## Multi-layer networks (example)

<div align="center"> <img src="https://www.dropbox.com/scl/fi/9djwmormk9sd1z5bqbu78/neural_network2.png?rlkey=303zkt9k5xrxwoakz4pnidumh&dl=1" width=550 height=550 /> </div>

- The input feeds **hidden layer 1**; its outputs feed **hidden layer 2**.
- The **output layer** can be **vector-valued** (multiple responses or class probabilities)—not limited to a single $Y$.



# Layers

- Neurons are grouped in **layers**; information flows (typically) from input → hidden → output.
- A **dense** (fully connected) layer connects **every** unit in the previous layer to **every** unit in the next—each edge has its own weight.

- Depth (many nonlinear layers) is what lets networks build rich **hierarchies** of features; **without** nonlinear activations, stacking affine maps would collapse to a single affine map.
- Modern architectures also use **specialized** layers (convolutions, attention, etc.) when the data have structure worth exploiting.


## Decisions to make to design a neural network

1. How many layers? 
2. How many neurons per layer? 
3. What function $h(X)$ do you use in each layer? 

**In-class exercise**

**Q6.** Holding data and training procedure fixed, if you **add layers** (more flexibility), you usually expect **bias** to ___ and **variance** to ___?


**Q7.** Same question if you **add neurons** per layer instead.




## Image recognition: convolutional neural networks (CNNs)

A photo is not a loose bag of numbers—it is a **grid** of pixels where **nearby** values usually belong together. **Convolutional neural networks (CNNs)** are the standard way deep learning respects that fact for **image classification**, **object detection**, **segmentation**, and similar tasks.


### Why not treat an image as one long list of pixels?

A **dense** layer wants to connect **every** input to **every** hidden unit. That is like giving every pixel its own private cable to every neuron—plausible for a handful of features, awkward for a million pixels.

What we *want* instead is closer to how we look at a picture: **local** patterns (edges, corners, textures) that **repeat** in different places. If the cat shifts a little left, we should not need a wholly new set of weights; the **same** little pattern detector should fire again after a shift.

**Scale check (illustration only).** A $224 \times 224$ RGB image has $224 \times 224 \times 3 = \text{150{,}528}$ raw inputs. One **dense** layer to **1,000** hidden units is already on the order of **150 million** weights for that layer alone—huge memory, slow to train, and easy to **overfit** unless data are massive.

**CNNs** encode a simple prior: use **small, shared** filters everywhere on the grid (**weight sharing** + **local connectivity**). Fewer parameters, and a bias toward **spatial** structure the data actually have.


### What is a convolution layer, in plain language?

Imagine a tiny **template** (a **kernel**, often $3 \times 3$) that you lay on top of the image at one spot. You multiply and add the overlapping numbers—one **score** for “how much does this neighborhood look like my template?” Then you **slide** the template to the next position and repeat. The result is a new **map** of scores across the image.

You learn **many** templates in parallel; each one becomes a **channel** (another slice of “what the network sees” at this layer). After a nonlinearity such as **ReLU**, those maps feed the next stage. You can treat **stride** and **padding** as bookkeeping for how far you step and what you do at the border—details you can look up when you implement.

**Concrete edge example (hand-picked numbers, not learned).** A **horizontal** edge is a place where brightness **jumps vertically** (e.g. dark above, bright below). A simple $3 \times 3$ pattern (Sobel-style) implements “**bottom row minus top row**” over three columns:

```
[-1  -1  -1]
[ 0   0   0]
[ 1   1   1]
```

You get a strong response along **horizontal** steps in the image. A **vertical** edge is the same story **left vs. right**:

```
[-1   0   1]
[-1   0   1]
[-1   0   1]
```

In real networks the entries are **learned**. Early layers often discover filters that **resemble** edge and texture detectors, because those are useful intermediate ingredients for recognizing objects.


### Pooling and the rhythm of a CNN

**Pooling** is a way to **downsample**: look at a small neighborhood (say $2 \times 2$) and summarize it with one number—**max pooling** keeps the **largest** activation in that patch. Intuitively: “if something fired strongly anywhere here, carry that signal forward,” while shrinking the map so deeper layers see a **coarser** grid.

A familiar **rhythm** is: **conv** → **nonlinearity** → **conv** → … → **pool**, repeated a few times. Early stages behave a bit like learned **edge/texture** banks; later stages combine those into **parts** and **object-level** cues. Again, the exact counts are engineering; the picture is **hierarchical features** built from local operations.


### From feature maps to a class label (sketch)

After several conv/pool blocks you still have **2D maps** (many channels, smaller height/width). For **classification**, the network usually **flattens** those maps into one long vector and passes them through one or more **dense** layers, ending in **softmax** (or logits) over classes—same “head” idea as a dense classifier, but the **body** is built from convolutions.

```
Image  →  [ Conv → ReLU → … → Pool ]  (repeat)
       →  Flatten  →  Dense  →  …  →  class scores
```

Hands-on: [TensorFlow — CNN image classification](https://www.tensorflow.org/tutorials/images/cnn) ( runnable in Colab from the page).


## Transformers (intuition)

**Transformers** are the main architecture behind modern **large language models** (chatbots, coding assistants) and show up in **vision** and **multimodal** systems too. You do not need to implement one in this course; the goal is a **rough picture** of how they differ from **dense** networks and **CNNs**.

- **CNNs** are built for **grids** (images): local filters + weight sharing.
- **Transformers** are built for **sequences** (text, time series, patches of an image): each position can **pull in information** from other positions in a **learned**, **data-dependent** way (**self-attention**).

**This section:** tokens → self-attention in words → what a **layer** stacks → how that connects to models like GPT.


### Sequences, tokens, embeddings

- Text is split into **tokens** (words or subword pieces). The model works on a **sequence** of tokens of **variable length**.
- Each token is mapped to a **dense vector** (a **learned embedding** plus optional **positional** information so “order” is not lost). So internally the network sees a **list of vectors**—one row per token.
- **Idea:** we want a **context-aware** representation of each token: the word “bank” should be represented differently in “river **bank**” vs “**bank** account.” That is what **self-attention** is for.


### Self-attention (the core idea)

- For **each** token, the model **scores** how relevant every other token is (including itself)—“who should I listen to for this position?” Those scores become **weights** that **sum to one** (after softmax), so they read like **attention** over the sequence.
- It then builds a **new vector** for that token as a **weighted mix** of the other tokens’ representations. Informally: **update my meaning using the rest of the sentence**.
- The comparisons are implemented with **matrix multiplications**, so the whole sequence can be processed **in parallel** on a GPU—unlike classic **RNNs**, which march left-to-right one step at a time.





**Optional visual:** Jay Alammar, [*The Illustrated Transformer*](https://jalammar.github.io/illustrated-transformer/).


## Advances in neural networks (why deep learning took off)

There is no single explanation—progress came from **algorithms**, **hardware**, **architectures suited to the data**, **more and better-used data**, and **practices** that control overfitting. 

### Optimization and software
- **Mini-batch stochastic gradient descent**, **momentum**, and **adaptive** optimizers made training large models on large data feasible.
- **Automatic differentiation** and modern frameworks (**TensorFlow**, **PyTorch**, …) made experimentation fast; many architectural ideas were old in theory but costly to try before this ecosystem existed.

### Hardware
- **GPUs** and **TPUs** make the dominant workload—**large matrix operations**—cheap enough that training huge networks became routine rather than exotic.

### Architectural ideas
- **Skip / residual connections** and **normalization** (BatchNorm, LayerNorm, …) made **very deep** networks much easier to train.
- **CNNs** use **local, shared** filters for **grid** data (especially images).
- **RNNs** and **LSTMs** once dominated **sequences**; **Transformers** and **self-attention** now power most large **language** models and appear across **vision** and **multimodal** systems.

### Data, pre-training, and scale
- Big **labeled** datasets (e.g. ImageNet) and **internet-scale** text showed what deep models can do when data are abundant.
- **Pre-training** + **fine-tuning** (**transfer learning**) reuses representations for new tasks—often the practical path when task-specific labels are scarce.
- **Self-supervised** learning (predict masked tokens, next word, distorted image views, …) uses **unlabeled** data to learn general features.
- **Scale** (parameters, data, compute) often improves performance

### Data quality, diversity, and bias
- Models **imitate the training distribution**: low-quality, one-sided, or duplicated content gets **reinforced**. (Train on mostly conspiracy narratives and you should expect conspiracy-shaped outputs; train on one book repeated endlessly and you should expect that book’s style and blind spots.)
- Better pipelines **curate** and **deduplicate**, aim for **representative** coverage where ethics and fairness matter, and monitor **toxic** or **biased** patterns rather than assuming “more data” automatically fixes them.

### Generalization and overfitting
- **Regularization:** **$L_2$ / weight decay**, **dropout**, **early stopping** on a **validation** set.
- **More (and more diverse) data** and **data augmentation** (cropping, noise, paraphrases, …) often beat clever tricks alone.
- For deep nets, **architecture choices** (depth, width) and **training recipe** (learning rate schedules, batch size) interact with bias–variance; **systematic validation** matters as much as for simpler learners.